"""add fts column

Revision ID: 1cbd4afefe7b
Revises: 10115be65ea4
Create Date: 2026-08-25 22:35:45.055292

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cbd4afefe7b'
down_revision: Union[str, Sequence[str], None] = '10115be65ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Hand-written, not autogenerated: a Postgres generated column is one
    of the cases `alembic revision --autogenerate` cannot express (it would
    either skip the column or write a plain one that never populates — see
    see the hybrid search notes). fts is GENERATED ALWAYS AS, computed by
    Postgres itself from content on every write."""
    op.execute(
        "ALTER TABLE chunks ADD COLUMN fts tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', content)) STORED"
    )
    op.create_index("ix_chunks_fts", "chunks", ["fts"],
                    postgresql_using="gin")


def downgrade() -> None:
    op.drop_index("ix_chunks_fts", table_name="chunks")
    op.drop_column("chunks", "fts")
