"""prompt versions

Revision ID: f402f27cb488
Revises: 20ef98450222
Create Date: 2026-09-01 11:53:29.160978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f402f27cb488'
down_revision: Union[str, Sequence[str], None] = '20ef98450222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_versions_name_version')
    )
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_index('ix_prompt_versions_one_active', 'prompt_versions', ['name'], unique=True, postgresql_where=sa.text('active'))
    # ### end Alembic commands ###

    RAG_ANSWER = """Answer the question using only the context below. If the answer
is not in the context, say you do not know. Cite the chunk numbers you used.

{context}

Question: {question}"""

    EVAL_JUDGE = """Question: {question}
Expected answer: {expected}
Actual answer: {actual}

Does the actual answer convey the expected fact? Reply exactly YES or NO."""

    SEED = [("rag_answer", RAG_ANSWER, ["context", "question"]),
            ("eval_judge", EVAL_JUDGE, ["question", "expected", "actual"])]

    prompts = sa.table("prompt_versions",
                       sa.column("name", sa.Text),
                       sa.column("version", sa.Integer),
                       sa.column("template", sa.Text),
                       sa.column("variables", postgresql.JSONB),
                       sa.column("active", sa.Boolean))
    op.bulk_insert(prompts, [
        {"name": n, "version": 1, "template": t,
         "variables": v, "active": True}
        for n, t, v in SEED])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_versions_one_active', table_name='prompt_versions', postgresql_where=sa.text('active'))
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
